# Variables
title:         "Calendar"
description:   "Responsive - Interactive Calendar Picker"
version:       5.0.6
url:           https://creativebulma.net/product/calendar/demo

# Build
markdown:      kramdown
permalink:     pretty
includes:      ['assets/css', 'assets/js']
exclude:       ['package.json']
sass:
  sass_dir:    _sass
  style:       compressed
